//! Generated stubs: encoding
//! Auto-generated by iv8-surface-codegen.
#![allow(unused_imports)]

use super::construct_only;
use v8::Local;
use v8::FunctionTemplate;

unsafe extern "C" fn text_decoder_op_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

/// Create FunctionTemplate for TextDecoder.
pub fn create_text_decoder_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "TextDecoder").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "TextDecoder").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // method: decode()
    {
        let name = v8::String::new(scope, "decode").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(text_decoder_op_1).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }

    tmpl
}

/// Create FunctionTemplate for TextDecoderStream.
pub fn create_text_decoder_stream_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "TextDecoderStream").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "TextDecoderStream").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }

    tmpl
}

unsafe extern "C" fn text_encoder_op_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::default_value_for_type(scope, "Uint8Array"));
    }));
}

unsafe extern "C" fn text_encoder_op_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

/// Create FunctionTemplate for TextEncoder.
pub fn create_text_encoder_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "TextEncoder").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "TextEncoder").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // method: encode()
    {
        let name = v8::String::new(scope, "encode").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(text_encoder_op_1).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: encodeInto()
    {
        let name = v8::String::new(scope, "encodeInto").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(text_encoder_op_2).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }

    tmpl
}

/// Create FunctionTemplate for TextEncoderStream.
pub fn create_text_encoder_stream_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "TextEncoderStream").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "TextEncoderStream").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }

    tmpl
}

