//! Generated stubs: observers
//! Auto-generated by iv8-surface-codegen.

use super::empty_constructor;
use v8::Local;
use v8::FunctionTemplate;

unsafe extern "C" fn intersection_observer_get_1(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn intersection_observer_get_2(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn intersection_observer_get_3(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn intersection_observer_get_4(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn intersection_observer_get_5(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn intersection_observer_get_6(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Boolean::new(scope, false).into());
    }));
}

unsafe extern "C" fn intersection_observer_op_7(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn intersection_observer_op_8(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn intersection_observer_op_9(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn intersection_observer_op_10(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

/// Create FunctionTemplate for IntersectionObserver.
pub fn create_intersection_observer_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(empty_constructor).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "IntersectionObserver").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "IntersectionObserver").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: root
    {
        let name = v8::String::new(scope, "root").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(intersection_observer_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: rootMargin
    {
        let name = v8::String::new(scope, "rootMargin").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(intersection_observer_get_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: scrollMargin
    {
        let name = v8::String::new(scope, "scrollMargin").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(intersection_observer_get_3).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: thresholds
    {
        let name = v8::String::new(scope, "thresholds").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(intersection_observer_get_4).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: delay
    {
        let name = v8::String::new(scope, "delay").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(intersection_observer_get_5).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: trackVisibility
    {
        let name = v8::String::new(scope, "trackVisibility").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(intersection_observer_get_6).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // method: observe()
    {
        let name = v8::String::new(scope, "observe").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(intersection_observer_op_7).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: unobserve()
    {
        let name = v8::String::new(scope, "unobserve").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(intersection_observer_op_8).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: disconnect()
    {
        let name = v8::String::new(scope, "disconnect").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(intersection_observer_op_9).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: takeRecords()
    {
        let name = v8::String::new(scope, "takeRecords").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(intersection_observer_op_10).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }

    tmpl
}

unsafe extern "C" fn intersection_observer_entry_get_1(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn intersection_observer_entry_get_2(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn intersection_observer_entry_get_3(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn intersection_observer_entry_get_4(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn intersection_observer_entry_get_5(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Boolean::new(scope, false).into());
    }));
}

unsafe extern "C" fn intersection_observer_entry_get_6(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Boolean::new(scope, false).into());
    }));
}

unsafe extern "C" fn intersection_observer_entry_get_7(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Number::new(scope, 0.0).into());
    }));
}

unsafe extern "C" fn intersection_observer_entry_get_8(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

/// Create FunctionTemplate for IntersectionObserverEntry.
pub fn create_intersection_observer_entry_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(empty_constructor).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "IntersectionObserverEntry").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "IntersectionObserverEntry").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: time
    {
        let name = v8::String::new(scope, "time").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(intersection_observer_entry_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: rootBounds
    {
        let name = v8::String::new(scope, "rootBounds").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(intersection_observer_entry_get_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: boundingClientRect
    {
        let name = v8::String::new(scope, "boundingClientRect").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(intersection_observer_entry_get_3).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: intersectionRect
    {
        let name = v8::String::new(scope, "intersectionRect").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(intersection_observer_entry_get_4).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: isIntersecting
    {
        let name = v8::String::new(scope, "isIntersecting").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(intersection_observer_entry_get_5).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: isVisible
    {
        let name = v8::String::new(scope, "isVisible").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(intersection_observer_entry_get_6).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: intersectionRatio
    {
        let name = v8::String::new(scope, "intersectionRatio").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(intersection_observer_entry_get_7).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: target
    {
        let name = v8::String::new(scope, "target").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(intersection_observer_entry_get_8).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }

    tmpl
}

unsafe extern "C" fn performance_observer_op_1(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn performance_observer_op_2(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn performance_observer_op_3(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn performance_observer_get_4(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

/// Create FunctionTemplate for PerformanceObserver.
pub fn create_performance_observer_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(empty_constructor).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "PerformanceObserver").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "PerformanceObserver").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // method: observe()
    {
        let name = v8::String::new(scope, "observe").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(performance_observer_op_1).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: disconnect()
    {
        let name = v8::String::new(scope, "disconnect").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(performance_observer_op_2).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: takeRecords()
    {
        let name = v8::String::new(scope, "takeRecords").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(performance_observer_op_3).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // attribute: supportedEntryTypes
    {
        let name = v8::String::new(scope, "supportedEntryTypes").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(performance_observer_get_4).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }

    tmpl
}

unsafe extern "C" fn pressure_observer_op_1(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn pressure_observer_op_2(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn pressure_observer_op_3(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn pressure_observer_op_4(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn pressure_observer_get_5(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

/// Create FunctionTemplate for PressureObserver.
pub fn create_pressure_observer_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(empty_constructor).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "PressureObserver").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "PressureObserver").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // method: observe()
    {
        let name = v8::String::new(scope, "observe").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(pressure_observer_op_1).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: unobserve()
    {
        let name = v8::String::new(scope, "unobserve").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(pressure_observer_op_2).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: disconnect()
    {
        let name = v8::String::new(scope, "disconnect").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(pressure_observer_op_3).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: takeRecords()
    {
        let name = v8::String::new(scope, "takeRecords").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(pressure_observer_op_4).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // attribute: knownSources
    {
        let name = v8::String::new(scope, "knownSources").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(pressure_observer_get_5).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }

    tmpl
}

unsafe extern "C" fn reporting_observer_op_1(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn reporting_observer_op_2(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn reporting_observer_op_3(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

/// Create FunctionTemplate for ReportingObserver.
pub fn create_reporting_observer_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(empty_constructor).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "ReportingObserver").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "ReportingObserver").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // method: observe()
    {
        let name = v8::String::new(scope, "observe").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(reporting_observer_op_1).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: disconnect()
    {
        let name = v8::String::new(scope, "disconnect").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(reporting_observer_op_2).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: takeRecords()
    {
        let name = v8::String::new(scope, "takeRecords").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(reporting_observer_op_3).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }

    tmpl
}

unsafe extern "C" fn resize_observer_op_1(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn resize_observer_op_2(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn resize_observer_op_3(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

/// Create FunctionTemplate for ResizeObserver.
pub fn create_resize_observer_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(empty_constructor).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "ResizeObserver").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "ResizeObserver").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // method: observe()
    {
        let name = v8::String::new(scope, "observe").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(resize_observer_op_1).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: unobserve()
    {
        let name = v8::String::new(scope, "unobserve").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(resize_observer_op_2).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: disconnect()
    {
        let name = v8::String::new(scope, "disconnect").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(resize_observer_op_3).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }

    tmpl
}

unsafe extern "C" fn resize_observer_entry_get_1(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn resize_observer_entry_get_2(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn resize_observer_entry_get_3(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn resize_observer_entry_get_4(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn resize_observer_entry_get_5(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

/// Create FunctionTemplate for ResizeObserverEntry.
pub fn create_resize_observer_entry_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(empty_constructor).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "ResizeObserverEntry").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "ResizeObserverEntry").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: target
    {
        let name = v8::String::new(scope, "target").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(resize_observer_entry_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: contentRect
    {
        let name = v8::String::new(scope, "contentRect").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(resize_observer_entry_get_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: borderBoxSize
    {
        let name = v8::String::new(scope, "borderBoxSize").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(resize_observer_entry_get_3).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: contentBoxSize
    {
        let name = v8::String::new(scope, "contentBoxSize").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(resize_observer_entry_get_4).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: devicePixelContentBoxSize
    {
        let name = v8::String::new(scope, "devicePixelContentBoxSize").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(resize_observer_entry_get_5).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }

    tmpl
}

unsafe extern "C" fn resize_observer_size_get_1(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Number::new(scope, 0.0).into());
    }));
}

unsafe extern "C" fn resize_observer_size_get_2(info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Number::new(scope, 0.0).into());
    }));
}

/// Create FunctionTemplate for ResizeObserverSize.
pub fn create_resize_observer_size_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(empty_constructor).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "ResizeObserverSize").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "ResizeObserverSize").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: inlineSize
    {
        let name = v8::String::new(scope, "inlineSize").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(resize_observer_size_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: blockSize
    {
        let name = v8::String::new(scope, "blockSize").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(resize_observer_size_get_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }

    tmpl
}

