//! Generated stubs: payment
//! Auto-generated by iv8-surface-codegen.
#![allow(unused_imports)]

use super::empty_constructor;
use v8::Local;
use v8::FunctionTemplate;

unsafe extern "C" fn payment_manager_get_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn payment_manager_set_1(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn payment_manager_op_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

/// Create FunctionTemplate for PaymentManager.
pub fn create_payment_manager_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(empty_constructor).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "PaymentManager").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "PaymentManager").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: userHint
    {
        let name = v8::String::new(scope, "userHint").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_manager_get_1).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(payment_manager_set_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // method: enableDelegations()
    {
        let name = v8::String::new(scope, "enableDelegations").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(payment_manager_op_2).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }

    tmpl
}

unsafe extern "C" fn payment_request_op_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn payment_request_op_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn payment_request_op_3(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn payment_request_get_4(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn payment_request_get_5(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn payment_request_get_6(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn payment_request_get_7(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn payment_request_get_8(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn payment_request_set_8(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn payment_request_get_9(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn payment_request_set_9(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn payment_request_get_10(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn payment_request_set_10(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn payment_request_op_11(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn payment_request_op_12(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

/// Create FunctionTemplate for PaymentRequest.
pub fn create_payment_request_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(empty_constructor).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "PaymentRequest").unwrap());
    if let Some(p) = _parent {
        tmpl.inherit(p);
    }

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "PaymentRequest").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // method: show()
    {
        let name = v8::String::new(scope, "show").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(payment_request_op_1).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: abort()
    {
        let name = v8::String::new(scope, "abort").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(payment_request_op_2).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: canMakePayment()
    {
        let name = v8::String::new(scope, "canMakePayment").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(payment_request_op_3).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // attribute: id
    {
        let name = v8::String::new(scope, "id").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_request_get_4).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: shippingAddress
    {
        let name = v8::String::new(scope, "shippingAddress").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_request_get_5).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: shippingOption
    {
        let name = v8::String::new(scope, "shippingOption").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_request_get_6).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: shippingType
    {
        let name = v8::String::new(scope, "shippingType").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_request_get_7).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: onshippingaddresschange
    {
        let name = v8::String::new(scope, "onshippingaddresschange").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_request_get_8).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(payment_request_set_8).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // attribute: onshippingoptionchange
    {
        let name = v8::String::new(scope, "onshippingoptionchange").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_request_get_9).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(payment_request_set_9).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // attribute: onpaymentmethodchange
    {
        let name = v8::String::new(scope, "onpaymentmethodchange").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_request_get_10).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(payment_request_set_10).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // method: securePaymentConfirmationAvailability()
    {
        let name = v8::String::new(scope, "securePaymentConfirmationAvailability").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(payment_request_op_11).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: getSecurePaymentConfirmationCapabilities()
    {
        let name = v8::String::new(scope, "getSecurePaymentConfirmationCapabilities").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(payment_request_op_12).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }

    tmpl
}

unsafe extern "C" fn payment_response_op_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn payment_response_get_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn payment_response_get_3(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn payment_response_get_4(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn payment_response_get_5(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn payment_response_get_6(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn payment_response_get_7(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn payment_response_get_8(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn payment_response_get_9(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn payment_response_op_10(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn payment_response_op_11(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn payment_response_get_12(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn payment_response_set_12(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

/// Create FunctionTemplate for PaymentResponse.
pub fn create_payment_response_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(empty_constructor).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "PaymentResponse").unwrap());
    if let Some(p) = _parent {
        tmpl.inherit(p);
    }

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "PaymentResponse").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // method: toJSON()
    {
        let name = v8::String::new(scope, "toJSON").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(payment_response_op_1).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // attribute: requestId
    {
        let name = v8::String::new(scope, "requestId").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_response_get_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: methodName
    {
        let name = v8::String::new(scope, "methodName").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_response_get_3).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: details
    {
        let name = v8::String::new(scope, "details").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_response_get_4).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: shippingAddress
    {
        let name = v8::String::new(scope, "shippingAddress").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_response_get_5).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: shippingOption
    {
        let name = v8::String::new(scope, "shippingOption").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_response_get_6).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: payerName
    {
        let name = v8::String::new(scope, "payerName").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_response_get_7).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: payerEmail
    {
        let name = v8::String::new(scope, "payerEmail").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_response_get_8).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: payerPhone
    {
        let name = v8::String::new(scope, "payerPhone").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_response_get_9).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // method: complete()
    {
        let name = v8::String::new(scope, "complete").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(payment_response_op_10).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: retry()
    {
        let name = v8::String::new(scope, "retry").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(payment_response_op_11).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // attribute: onpayerdetailchange
    {
        let name = v8::String::new(scope, "onpayerdetailchange").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(payment_response_get_12).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(payment_response_set_12).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }

    tmpl
}

