//! Generated stubs: url
//! Auto-generated by iv8-surface-codegen.

use super::empty_constructor;
use v8::Local;
use v8::FunctionTemplate;

unsafe extern "C" fn url_op_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn url_op_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Boolean::new(scope, false).into());
    }));
}

unsafe extern "C" fn url_get_3(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn url_set_3(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn url_get_4(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn url_get_5(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn url_set_5(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn url_get_6(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn url_set_6(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn url_get_7(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn url_set_7(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn url_get_8(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn url_set_8(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn url_get_9(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn url_set_9(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn url_get_10(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn url_set_10(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn url_get_11(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn url_set_11(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn url_get_12(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn url_set_12(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn url_get_13(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn url_get_14(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn url_set_14(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn url_op_15(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn url_op_16(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn url_op_17(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

/// Create FunctionTemplate for URL.
pub fn create_url_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(empty_constructor).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "URL").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "URL").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // method: parse()
    {
        let name = v8::String::new(scope, "parse").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(url_op_1).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: canParse()
    {
        let name = v8::String::new(scope, "canParse").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(url_op_2).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // attribute: href
    {
        let name = v8::String::new(scope, "href").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(url_get_3).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(url_set_3).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // attribute: origin
    {
        let name = v8::String::new(scope, "origin").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(url_get_4).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: protocol
    {
        let name = v8::String::new(scope, "protocol").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(url_get_5).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(url_set_5).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // attribute: username
    {
        let name = v8::String::new(scope, "username").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(url_get_6).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(url_set_6).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // attribute: password
    {
        let name = v8::String::new(scope, "password").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(url_get_7).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(url_set_7).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // attribute: host
    {
        let name = v8::String::new(scope, "host").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(url_get_8).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(url_set_8).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // attribute: hostname
    {
        let name = v8::String::new(scope, "hostname").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(url_get_9).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(url_set_9).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // attribute: port
    {
        let name = v8::String::new(scope, "port").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(url_get_10).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(url_set_10).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // attribute: pathname
    {
        let name = v8::String::new(scope, "pathname").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(url_get_11).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(url_set_11).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // attribute: search
    {
        let name = v8::String::new(scope, "search").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(url_get_12).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(url_set_12).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // attribute: searchParams
    {
        let name = v8::String::new(scope, "searchParams").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(url_get_13).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: hash
    {
        let name = v8::String::new(scope, "hash").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(url_get_14).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(url_set_14).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // method: toJSON()
    {
        let name = v8::String::new(scope, "toJSON").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(url_op_15).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: createObjectURL()
    {
        let name = v8::String::new(scope, "createObjectURL").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(url_op_16).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: revokeObjectURL()
    {
        let name = v8::String::new(scope, "revokeObjectURL").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(url_op_17).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }

    tmpl
}

unsafe extern "C" fn url_search_params_get_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn url_search_params_op_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn url_search_params_op_3(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn url_search_params_op_4(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn url_search_params_op_5(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn url_search_params_op_6(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Boolean::new(scope, false).into());
    }));
}

unsafe extern "C" fn url_search_params_op_7(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn url_search_params_op_8(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn url_search_params_op_9(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

/// Create FunctionTemplate for URLSearchParams.
pub fn create_url_search_params_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(empty_constructor).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "URLSearchParams").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "URLSearchParams").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: size
    {
        let name = v8::String::new(scope, "size").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(url_search_params_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // method: append()
    {
        let name = v8::String::new(scope, "append").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(url_search_params_op_2).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: delete()
    {
        let name = v8::String::new(scope, "delete").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(url_search_params_op_3).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: get()
    {
        let name = v8::String::new(scope, "get").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(url_search_params_op_4).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: getAll()
    {
        let name = v8::String::new(scope, "getAll").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(url_search_params_op_5).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: has()
    {
        let name = v8::String::new(scope, "has").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(url_search_params_op_6).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: set()
    {
        let name = v8::String::new(scope, "set").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(url_search_params_op_7).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: sort()
    {
        let name = v8::String::new(scope, "sort").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(url_search_params_op_8).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: unknown()
    {
        let name = v8::String::new(scope, "unknown").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(url_search_params_op_9).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }

    tmpl
}

