//! Generated stubs: usb
//! Auto-generated by iv8-surface-codegen.
#![allow(unused_imports)]

use super::construct_only;
use v8::Local;
use v8::FunctionTemplate;

unsafe extern "C" fn usb_alternate_interface_get_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_alternate_interface_get_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_alternate_interface_get_3(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_alternate_interface_get_4(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_alternate_interface_get_5(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn usb_alternate_interface_get_6(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

/// Create FunctionTemplate for USBAlternateInterface.
pub fn create_usb_alternate_interface_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "USBAlternateInterface").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "USBAlternateInterface").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: alternateSetting
    {
        let name = v8::String::new(scope, "alternateSetting").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_alternate_interface_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: interfaceClass
    {
        let name = v8::String::new(scope, "interfaceClass").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_alternate_interface_get_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: interfaceSubclass
    {
        let name = v8::String::new(scope, "interfaceSubclass").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_alternate_interface_get_3).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: interfaceProtocol
    {
        let name = v8::String::new(scope, "interfaceProtocol").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_alternate_interface_get_4).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: interfaceName
    {
        let name = v8::String::new(scope, "interfaceName").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_alternate_interface_get_5).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: endpoints
    {
        let name = v8::String::new(scope, "endpoints").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_alternate_interface_get_6).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }

    tmpl
}

unsafe extern "C" fn usb_configuration_get_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_configuration_get_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn usb_configuration_get_3(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

/// Create FunctionTemplate for USBConfiguration.
pub fn create_usb_configuration_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "USBConfiguration").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "USBConfiguration").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: configurationValue
    {
        let name = v8::String::new(scope, "configurationValue").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_configuration_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: configurationName
    {
        let name = v8::String::new(scope, "configurationName").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_configuration_get_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: interfaces
    {
        let name = v8::String::new(scope, "interfaces").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_configuration_get_3).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }

    tmpl
}

unsafe extern "C" fn usb_device_get_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_device_get_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_device_get_3(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_device_get_4(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_device_get_5(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_device_get_6(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_device_get_7(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_device_get_8(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_device_get_9(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_device_get_10(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_device_get_11(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_device_get_12(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn usb_device_get_13(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn usb_device_get_14(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::v8_str(scope, ""));
    }));
}

unsafe extern "C" fn usb_device_get_15(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn usb_device_get_16(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_device_get_17(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Boolean::new(scope, false).into());
    }));
}

unsafe extern "C" fn usb_device_op_18(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_device_op_19(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_device_op_20(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_device_op_21(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_device_op_22(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_device_op_23(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_device_op_24(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_device_op_25(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_device_op_26(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_device_op_27(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_device_op_28(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_device_op_29(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_device_op_30(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_device_op_31(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_device_op_32(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

/// Create FunctionTemplate for USBDevice.
pub fn create_usb_device_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "USBDevice").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "USBDevice").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: usbVersionMajor
    {
        let name = v8::String::new(scope, "usbVersionMajor").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: usbVersionMinor
    {
        let name = v8::String::new(scope, "usbVersionMinor").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: usbVersionSubminor
    {
        let name = v8::String::new(scope, "usbVersionSubminor").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_3).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: deviceClass
    {
        let name = v8::String::new(scope, "deviceClass").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_4).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: deviceSubclass
    {
        let name = v8::String::new(scope, "deviceSubclass").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_5).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: deviceProtocol
    {
        let name = v8::String::new(scope, "deviceProtocol").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_6).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: vendorId
    {
        let name = v8::String::new(scope, "vendorId").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_7).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: productId
    {
        let name = v8::String::new(scope, "productId").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_8).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: deviceVersionMajor
    {
        let name = v8::String::new(scope, "deviceVersionMajor").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_9).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: deviceVersionMinor
    {
        let name = v8::String::new(scope, "deviceVersionMinor").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_10).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: deviceVersionSubminor
    {
        let name = v8::String::new(scope, "deviceVersionSubminor").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_11).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: manufacturerName
    {
        let name = v8::String::new(scope, "manufacturerName").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_12).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: productName
    {
        let name = v8::String::new(scope, "productName").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_13).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: serialNumber
    {
        let name = v8::String::new(scope, "serialNumber").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_14).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: configuration
    {
        let name = v8::String::new(scope, "configuration").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_15).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: configurations
    {
        let name = v8::String::new(scope, "configurations").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_16).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: opened
    {
        let name = v8::String::new(scope, "opened").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_device_get_17).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // method: open()
    {
        let name = v8::String::new(scope, "open").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_device_op_18).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: close()
    {
        let name = v8::String::new(scope, "close").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_device_op_19).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: forget()
    {
        let name = v8::String::new(scope, "forget").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_device_op_20).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: selectConfiguration()
    {
        let name = v8::String::new(scope, "selectConfiguration").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_device_op_21).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: claimInterface()
    {
        let name = v8::String::new(scope, "claimInterface").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_device_op_22).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: releaseInterface()
    {
        let name = v8::String::new(scope, "releaseInterface").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_device_op_23).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: selectAlternateInterface()
    {
        let name = v8::String::new(scope, "selectAlternateInterface").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_device_op_24).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: controlTransferIn()
    {
        let name = v8::String::new(scope, "controlTransferIn").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_device_op_25).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: controlTransferOut()
    {
        let name = v8::String::new(scope, "controlTransferOut").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_device_op_26).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: clearHalt()
    {
        let name = v8::String::new(scope, "clearHalt").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_device_op_27).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: transferIn()
    {
        let name = v8::String::new(scope, "transferIn").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_device_op_28).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: transferOut()
    {
        let name = v8::String::new(scope, "transferOut").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_device_op_29).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: isochronousTransferIn()
    {
        let name = v8::String::new(scope, "isochronousTransferIn").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_device_op_30).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: isochronousTransferOut()
    {
        let name = v8::String::new(scope, "isochronousTransferOut").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_device_op_31).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: reset()
    {
        let name = v8::String::new(scope, "reset").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_device_op_32).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }

    tmpl
}

unsafe extern "C" fn usb_endpoint_get_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_endpoint_get_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn usb_endpoint_get_3(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn usb_endpoint_get_4(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

/// Create FunctionTemplate for USBEndpoint.
pub fn create_usb_endpoint_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "USBEndpoint").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "USBEndpoint").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: endpointNumber
    {
        let name = v8::String::new(scope, "endpointNumber").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_endpoint_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: direction
    {
        let name = v8::String::new(scope, "direction").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_endpoint_get_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: type
    {
        let name = v8::String::new(scope, "type").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_endpoint_get_3).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: packetSize
    {
        let name = v8::String::new(scope, "packetSize").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_endpoint_get_4).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }

    tmpl
}

unsafe extern "C" fn usb_in_transfer_result_get_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::default_value_for_type(scope, "DataView"));
    }));
}

unsafe extern "C" fn usb_in_transfer_result_get_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

/// Create FunctionTemplate for USBInTransferResult.
pub fn create_usb_in_transfer_result_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "USBInTransferResult").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "USBInTransferResult").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: data
    {
        let name = v8::String::new(scope, "data").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_in_transfer_result_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: status
    {
        let name = v8::String::new(scope, "status").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_in_transfer_result_get_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }

    tmpl
}

unsafe extern "C" fn usb_interface_get_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_interface_get_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn usb_interface_get_3(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_interface_get_4(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Boolean::new(scope, false).into());
    }));
}

/// Create FunctionTemplate for USBInterface.
pub fn create_usb_interface_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "USBInterface").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "USBInterface").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: interfaceNumber
    {
        let name = v8::String::new(scope, "interfaceNumber").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_interface_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: alternate
    {
        let name = v8::String::new(scope, "alternate").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_interface_get_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: alternates
    {
        let name = v8::String::new(scope, "alternates").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_interface_get_3).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: claimed
    {
        let name = v8::String::new(scope, "claimed").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_interface_get_4).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }

    tmpl
}

unsafe extern "C" fn usb_isochronous_in_transfer_packet_get_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::default_value_for_type(scope, "DataView"));
    }));
}

unsafe extern "C" fn usb_isochronous_in_transfer_packet_get_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

/// Create FunctionTemplate for USBIsochronousInTransferPacket.
pub fn create_usb_isochronous_in_transfer_packet_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "USBIsochronousInTransferPacket").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "USBIsochronousInTransferPacket").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: data
    {
        let name = v8::String::new(scope, "data").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_isochronous_in_transfer_packet_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: status
    {
        let name = v8::String::new(scope, "status").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_isochronous_in_transfer_packet_get_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }

    tmpl
}

unsafe extern "C" fn usb_isochronous_in_transfer_result_get_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(crate::type_conv::default_value_for_type(scope, "DataView"));
    }));
}

unsafe extern "C" fn usb_isochronous_in_transfer_result_get_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

/// Create FunctionTemplate for USBIsochronousInTransferResult.
pub fn create_usb_isochronous_in_transfer_result_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "USBIsochronousInTransferResult").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "USBIsochronousInTransferResult").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: data
    {
        let name = v8::String::new(scope, "data").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_isochronous_in_transfer_result_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: packets
    {
        let name = v8::String::new(scope, "packets").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_isochronous_in_transfer_result_get_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }

    tmpl
}

unsafe extern "C" fn usb_isochronous_out_transfer_packet_get_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_isochronous_out_transfer_packet_get_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

/// Create FunctionTemplate for USBIsochronousOutTransferPacket.
pub fn create_usb_isochronous_out_transfer_packet_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "USBIsochronousOutTransferPacket").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "USBIsochronousOutTransferPacket").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: bytesWritten
    {
        let name = v8::String::new(scope, "bytesWritten").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_isochronous_out_transfer_packet_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: status
    {
        let name = v8::String::new(scope, "status").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_isochronous_out_transfer_packet_get_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }

    tmpl
}

unsafe extern "C" fn usb_isochronous_out_transfer_result_get_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

/// Create FunctionTemplate for USBIsochronousOutTransferResult.
pub fn create_usb_isochronous_out_transfer_result_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "USBIsochronousOutTransferResult").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "USBIsochronousOutTransferResult").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: packets
    {
        let name = v8::String::new(scope, "packets").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_isochronous_out_transfer_result_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }

    tmpl
}

unsafe extern "C" fn usb_out_transfer_result_get_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Integer::new(scope, 0).into());
    }));
}

unsafe extern "C" fn usb_out_transfer_result_get_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

/// Create FunctionTemplate for USBOutTransferResult.
pub fn create_usb_out_transfer_result_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "USBOutTransferResult").unwrap());

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "USBOutTransferResult").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: bytesWritten
    {
        let name = v8::String::new(scope, "bytesWritten").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_out_transfer_result_get_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }
    // attribute: status
    {
        let name = v8::String::new(scope, "status").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_out_transfer_result_get_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);
    }

    tmpl
}

unsafe extern "C" fn usb_get_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn usb_set_1(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn usb_get_2(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::Object::new(scope).into());
    }));
}

unsafe extern "C" fn usb_set_2(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

unsafe extern "C" fn usb_op_3(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_op_4(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

/// Create FunctionTemplate for USB.
pub fn create_usb_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "USB").unwrap());
    if let Some(p) = _parent {
        tmpl.inherit(p);
    }

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "USB").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: onconnect
    {
        let name = v8::String::new(scope, "onconnect").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_get_1).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(usb_set_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // attribute: ondisconnect
    {
        let name = v8::String::new(scope, "ondisconnect").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_get_2).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(usb_set_2).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }
    // method: getDevices()
    {
        let name = v8::String::new(scope, "getDevices").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_op_3).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }
    // method: requestDevice()
    {
        let name = v8::String::new(scope, "requestDevice").unwrap();
        let func_tmpl = v8::FunctionTemplate::builder_raw(usb_op_4).build(scope);
        func_tmpl.set_class_name(name);
        proto.set(name.into(), func_tmpl.into());
    }

    tmpl
}

unsafe extern "C" fn usb_permission_result_get_1(_info: *const v8::FunctionCallbackInfo) {
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let info_ref = unsafe { &*_info };
        v8::callback_scope!(unsafe scope, info_ref);
        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);
        rv.set(v8::undefined(scope).into());
    }));
}

unsafe extern "C" fn usb_permission_result_set_1(_info: *const v8::FunctionCallbackInfo) {
    // no-op setter stub
}

/// Create FunctionTemplate for USBPermissionResult.
pub fn create_usb_permission_result_template<'s>(
    scope: &v8::PinScope<'s, '_>,
    _parent: Option<v8::Local<'s, v8::FunctionTemplate>>,
) -> v8::Local<'s, v8::FunctionTemplate> {
    let tmpl = v8::FunctionTemplate::builder_raw(construct_only).build(scope);
    tmpl.set_class_name(v8::String::new(scope, "USBPermissionResult").unwrap());
    if let Some(p) = _parent {
        tmpl.inherit(p);
    }

    let proto = tmpl.prototype_template(scope);
    {
        let tag_sym = v8::Symbol::get_to_string_tag(scope);
        let tag_val = v8::String::new(scope, "USBPermissionResult").unwrap();
        proto.set(tag_sym.into(), tag_val.into());
    }
    // attribute: devices
    {
        let name = v8::String::new(scope, "devices").unwrap();
        let getter = v8::FunctionTemplate::builder_raw(usb_permission_result_get_1).build(scope);
        let setter = v8::FunctionTemplate::builder_raw(usb_permission_result_set_1).build(scope);
        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);
    }

    tmpl
}

