//! Code generation engine — generates Rust source for FunctionTemplate stubs.
//!
//! Converts IR definitions into compilable Rust code for the iv8-surface crate.
//! Each interface becomes a `pub fn create_<name>_template()` function.

use crate::ir::{Definition, MemberData};
use crate::type_mapper;
use crate::ea_handler::{EaResult, process_interface_ea};
use std::collections::BTreeMap;

/// A generated Rust source file with domain-grouped modules.
pub struct GeneratedFile {
    pub domain: String,
    pub content: String,
    pub interface_count: usize,
    pub member_count: usize,
}

/// Generate all domain files from merged definitions.
pub fn generate_all(definitions: &[Definition], sorted: &[String]) -> Vec<GeneratedFile> {
    let mut by_name: BTreeMap<String, &Definition> = BTreeMap::new();
    for def in definitions {
        if let Some(name) = &def.name {
            if def.kind != "interface" { continue; }
            by_name.insert(name.clone(), def);
        }
    }

    // Group by domain
    let mut domains: BTreeMap<String, Vec<&Definition>> = BTreeMap::new();
    for name in sorted {
        if let Some(def) = by_name.get(name) {
            let domain = crate::topo::classify_domain(name).to_string();
            domains.entry(domain).or_default().push(def);
        }
    }

    let mut files = Vec::new();
    for (domain, defs) in &domains {
        let content = generate_domain_file(domain, defs, &by_name);
        files.push(GeneratedFile {
            domain: domain.clone(),
            content,
            interface_count: defs.len(),
            member_count: defs.iter().map(|d| d.members.len()).sum(),
        });
    }
    files
}

fn generate_domain_file(
    domain: &str,
    defs: &[&Definition],
    _all: &BTreeMap<String, &Definition>,
) -> String {
    let mut out = String::new();
    out.push_str(&format!("//! Generated FunctionTemplate stubs for {}.\n", domain));
    out.push_str("//! Auto-generated by iv8-surface-codegen — do not edit by hand.\n\n");
    out.push_str("use v8::Local;\n");
    out.push_str("use v8::FunctionTemplate;\n");
    out.push_str("use v8::Object;\n\n");

    // Shared empty constructor for this domain
    out.push_str("unsafe extern \"C\" fn empty_constructor(_info: *const v8::FunctionCallbackInfo) {\n");
    out.push_str("    // No-op: instances created by Rust\n");
    out.push_str("}\n\n");

    for def in defs {
        let name = match &def.name {
            Some(n) => n,
            None => continue,
        };
        let fn_name = type_mapper::idl_name_to_rust(name);
        let ea = process_interface_ea(def);

        out.push_str(&generate_template_function(def, &ea, &fn_name));
        out.push('\n');
        out.push_str(&generate_callback_functions(def, &fn_name));
    }

    // Generate install_all function
    out.push_str(&format!(
        "/// Install all {} stubs.\n", domain));
    out.push_str("pub fn install_all(_scope: &v8::PinScope<'_, '_>, _global: Local<Object>) {\n");
    for def in defs {
        let name = match &def.name {
            Some(n) => n,
            None => continue,
        };
        let fn_name = type_mapper::idl_name_to_rust(name);
        out.push_str(&format!("    // create_{}_template(scope, None); // TODO: wire parent\n", fn_name));
    }
    out.push_str("}\n");

    out
}

fn generate_template_function(def: &Definition, _ea: &EaResult, fn_name: &str) -> String {
    let name = def.name.as_deref().unwrap_or("Unknown");
    let mut out = String::new();

    out.push_str(&format!(
        "/// Create the FunctionTemplate for {}.\n", name));
    out.push_str(&format!(
        "pub fn create_{}_template<'s>(\n", fn_name));
    out.push_str("    scope: &v8::PinScope<'s, '_>,\n");

    if let Some(_parent) = &def.inheritance {
        out.push_str("    parent: Option<v8::Local<'s, v8::FunctionTemplate>>,\n");
    }

    out.push_str(") -> v8::Local<'s, v8::FunctionTemplate> {\n");
    out.push_str("    let tmpl = v8::FunctionTemplate::builder_raw(empty_constructor).build(scope);\n");
    out.push_str(&format!(
        "    tmpl.set_class_name(v8::String::new(scope, \"{}\").unwrap());\n", name));

    // Inheritance
    if def.inheritance.is_some() {
        out.push_str("    if let Some(p) = parent {\n");
        out.push_str("        tmpl.inherit(p);\n");
        out.push_str("    }\n");
    }

    // Prototype accessors
    let proto_needed = def.members.iter().any(|m| m.kind == "attribute" || m.kind == "operation");
    if proto_needed {
        out.push_str("\n    let proto = tmpl.prototype_template(scope);\n");
    }

    // Generate attribute getters
    let mut getter_idx = 0;
    for member in &def.members {
        if member.kind == "attribute" {
            getter_idx += 1;
            let attr_name = member.name.as_deref().unwrap_or("unknown");
            let _type_map = type_mapper::map_idl_type(member.idl_type.as_deref().unwrap_or("any"));
            let getter_fn = format!("{}_get_{}", fn_name, getter_idx);

            // Install accessor on prototype
            let name_str = type_mapper::escape_rust_keyword(attr_name);
            out.push_str(&format!(
                "    {{\n"));
            out.push_str(&format!(
                "        let name = v8::String::new(scope, \"{}\").unwrap();\n", attr_name));
            out.push_str(&format!(
                "        let getter = v8::FunctionTemplate::builder_raw({}).build(scope);\n", getter_fn));
            out.push_str("        proto.set_accessor_property(\n");
            out.push_str("            name.into(),\n");
            out.push_str("            Some(getter),\n");
            out.push_str("            None,\n");
            out.push_str("            v8::PropertyAttribute::NONE,\n");
            out.push_str("        );\n");
            out.push_str("    }\n");
        }

        if member.kind == "operation" {
            let op_name = member.name.as_deref().unwrap_or("unknown");
            out.push_str(&format!(
                "    // operation: {}() — stub (returns default)\n", op_name));
            out.push_str(&format!(
                "    // proto.set(crate::type_conv::v8_str(scope, \"{}\"), ...);\n", op_name));
        }
    }

    out.push_str("\n    tmpl\n");
    out.push_str("}\n");
    out
}

fn generate_callback_functions(def: &Definition, fn_name: &str) -> String {
    let mut out = String::new();
    let mut getter_idx = 0;

    for member in &def.members {
        if member.kind != "attribute" { continue; }

        getter_idx += 1;
        let getter_fn = format!("{}_get_{}", fn_name, getter_idx);
        let type_map = type_mapper::map_idl_type(member.idl_type.as_deref().unwrap_or("any"));

        out.push_str(&format!(
            "unsafe extern \"C\" fn {}(info: *const v8::FunctionCallbackInfo) {{\n", getter_fn));
        out.push_str("    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {\n");
        out.push_str("        let info_ref = unsafe { &*info };\n");
        out.push_str("        v8::callback_scope!(unsafe scope, info_ref);\n");
        out.push_str("        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);\n");
        out.push_str(&format!("        rv.set({});\n", type_map.default_value));
        out.push_str("    }));\n");
        out.push_str("}\n\n");
    }

    out
}

/// Generate mod.rs that aggregates all domain modules.
pub fn generate_mod_rs(domains: &[String]) -> String {
    let mut out = String::new();
    out.push_str("//! Generated FunctionTemplate stubs — auto-generated by iv8-surface-codegen.\n\n");

    for domain in domains {
        out.push_str(&format!("pub mod {};\n", domain));
    }

    out.push_str("\nuse v8::Local;\nuse v8::Object;\n\n");
    out.push_str("/// Install all generated stubs in topological order.\n");
    out.push_str("pub fn install_all(scope: &v8::PinScope<'_, '_>, global: Local<Object>) {\n");

    for domain in domains {
        out.push_str(&format!("    {}::install_all(scope, global);\n", domain));
    }

    out.push_str("}\n");
    out
}

/// Empty constructor callback shared by all generated templates.
pub fn empty_constructor_code() -> &'static str {
    "unsafe extern \"C\" fn empty_constructor(_info: *const v8::FunctionCallbackInfo) {\n    // No-op: instances created by Rust, not constructable from JS\n}\n"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_simple_interface() {
        let def = Definition {
            kind: "interface".into(),
            name: Some("TestInterface".into()),
            source: Some("w3c".into()),
            inheritance: None,
            ext_attrs: vec![],
            members: vec![
                MemberData {
                    kind: "attribute".into(),
                    name: Some("testAttr".into()),
                    idl_type: Some("DOMString".into()),
                    readonly: false,
                    return_type: None,
                    arguments: vec![],
                },
            ],
            partial: false,
            values: vec![],
            target: None,
            includes: None,
        };

        let files = generate_all(&[def], &["TestInterface".into()]);
        assert_eq!(files.len(), 1);
        assert!(files[0].content.contains("create_test_interface_template"));
        assert!(files[0].content.contains("testAttr"));
    }
}
