//! Code generation engine — generates Rust source for FunctionTemplate stubs.

use crate::ir::{Definition, MemberData};
use crate::type_mapper;
use crate::ea_handler::{EaResult, process_interface_ea};
use std::collections::BTreeMap;

pub struct GeneratedFile {
    pub domain: String,
    pub content: String,
    pub interface_count: usize,
    pub member_count: usize,
}

pub struct InstallInfo {
    /// Topologically sorted interface names
    pub sorted: Vec<String>,
    /// name → domain
    pub domain_of: BTreeMap<String, String>,
}

/// Generate all domain files + install info from merged definitions.
pub fn generate_all(definitions: &[Definition], sorted: &[String]) -> (Vec<GeneratedFile>, InstallInfo) {
    let mut by_name: BTreeMap<String, &Definition> = BTreeMap::new();
    for def in definitions {
        if let Some(name) = &def.name {
            if def.kind != "interface" { continue; }
            by_name.insert(name.clone(), def);
        }
    }

    let mut domains: BTreeMap<String, Vec<&Definition>> = BTreeMap::new();
    let mut domain_of = BTreeMap::new();
    for name in sorted {
        if let Some(def) = by_name.get(name) {
            let domain = crate::topo::classify_domain(name).to_string();
            domains.entry(domain.clone()).or_default().push(def);
            domain_of.insert(name.clone(), domain);
        }
    }

    let mut files = Vec::new();
    for (domain, defs) in &domains {
        let content = generate_domain_file(domain, defs, &by_name);
        files.push(GeneratedFile {
            domain: domain.clone(),
            content,
            interface_count: defs.len(),
            member_count: defs.iter().map(|d| d.members.len()).sum(),
        });
    }
    files.sort_by(|a, b| a.domain.cmp(&b.domain));

    let sorted_interfaces: Vec<String> = sorted.iter()
        .filter(|n| by_name.contains_key(*n))
        .cloned()
        .collect();

    (files, InstallInfo { sorted: sorted_interfaces, domain_of })
}

fn generate_domain_file(domain: &str, defs: &[&Definition], all: &BTreeMap<String, &Definition>) -> String {
    let mut out = String::new();
    out.push_str(&format!("//! Generated stubs: {}\n", domain));
    out.push_str("//! Auto-generated by iv8-surface-codegen.\n\n");
    out.push_str("use v8::Local;\n");
    out.push_str("use v8::FunctionTemplate;\n\n");
    out.push_str("unsafe extern \"C\" fn empty_constructor(_info: *const v8::FunctionCallbackInfo) {}\n\n");

    for def in defs {
        let name = match &def.name { Some(n) => n, None => continue };
        let fn_name = type_mapper::idl_name_to_rust(name);
        let ea = process_interface_ea(def);

        // Callback functions first (must be defined before template functions that reference them)
        let callbacks = generate_callbacks(def, &fn_name);
        if !callbacks.is_empty() {
            out.push_str(&callbacks);
        }
        out.push_str(&generate_template_function(def, &ea, &fn_name));
        out.push('\n');
    }

    out
}

fn generate_callbacks(def: &Definition, fn_name: &str) -> String {
    let mut out = String::new();
    let mut idx = 0;

    for m in &def.members {
        if m.kind == "attribute" {
            idx += 1;
            let type_name = m.idl_type.as_deref().unwrap_or("any");
            let tm = type_mapper::map_idl_type(type_name);

            // Getter
            out.push_str(&format!(
                "unsafe extern \"C\" fn {}_get_{}(info: *const v8::FunctionCallbackInfo) {{\n", fn_name, idx));
            out.push_str("    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {\n");
            out.push_str("        let info_ref = unsafe { &*info };\n");
            out.push_str("        v8::callback_scope!(unsafe scope, info_ref);\n");
            out.push_str("        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);\n");
            out.push_str(&format!("        rv.set({});\n", tm.default_value));
            out.push_str("    }));\n");
            out.push_str("}\n\n");

            // Setter for non-readonly attributes
            if !m.readonly {
                out.push_str(&format!(
                    "unsafe extern \"C\" fn {}_set_{}(info: *const v8::FunctionCallbackInfo) {{\n", fn_name, idx));
                out.push_str("    // no-op setter stub\n");
                out.push_str("}\n\n");
            }
        }

        if m.kind == "operation" {
            idx += 1;
            let ret_name = m.return_type.as_deref().unwrap_or("undefined");
            let tm = type_mapper::map_idl_type(ret_name);
            out.push_str(&format!(
                "unsafe extern \"C\" fn {}_op_{}(info: *const v8::FunctionCallbackInfo) {{\n", fn_name, idx));
            out.push_str("    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {\n");
            out.push_str("        let info_ref = unsafe { &*info };\n");
            out.push_str("        v8::callback_scope!(unsafe scope, info_ref);\n");
            out.push_str("        let mut rv = v8::ReturnValue::from_function_callback_info(info_ref);\n");
            out.push_str(&format!("        rv.set({});\n", tm.default_value));
            out.push_str("    }));\n");
            out.push_str("}\n\n");
        }
    }
    out
}

fn generate_template_function(def: &Definition, _ea: &EaResult, fn_name: &str) -> String {
    let name = def.name.as_deref().unwrap_or("Unknown");
    let mut out = String::new();

    // Determine parent create function name for cross-referencing
    let parent_fn = def.inheritance.as_ref()
        .map(|p| format!("{}::create_{}_template", crate::topo::classify_domain(p).replace('-', "_"), type_mapper::idl_name_to_rust(p)));

    out.push_str(&format!("/// Create FunctionTemplate for {}.\n", name));
    out.push_str(&format!("pub fn create_{}_template<'s>(\n", fn_name));
    out.push_str("    scope: &v8::PinScope<'s, '_>,\n");
    out.push_str("    parent: Option<v8::Local<'s, v8::FunctionTemplate>>,\n");
    out.push_str(") -> v8::Local<'s, v8::FunctionTemplate> {\n");
    out.push_str("    let tmpl = v8::FunctionTemplate::builder_raw(empty_constructor).build(scope);\n");
    out.push_str(&format!("    tmpl.set_class_name(v8::String::new(scope, \"{}\").unwrap());\n", name));

    // Inheritance
    if def.inheritance.is_some() {
        out.push_str("    if let Some(p) = parent {\n");
        out.push_str("        tmpl.inherit(p);\n");
        out.push_str("    }\n");
    }

    // Prototype setup
    let has_members = !def.members.is_empty();
    out.push_str("\n    let proto = tmpl.prototype_template(scope);\n");

    // Symbol.toStringTag
    out.push_str("    {\n");
    out.push_str("        let tag_sym = v8::Symbol::get_to_string_tag(scope);\n");
    out.push_str(&format!("        let tag_val = v8::String::new(scope, \"{}\").unwrap();\n", name));
    out.push_str("        proto.set(tag_sym.into(), tag_val.into());\n");
    out.push_str("    }\n");

    // Members — only generate for attribute and operation
    let mut idx = 0;
    for m in &def.members {
        if m.kind != "attribute" && m.kind != "operation" {
            continue;
        }
        idx += 1;
        if m.kind == "attribute" {
            let attr_name = m.name.as_deref().unwrap_or("unknown");
            out.push_str(&format!(
                "    // attribute: {}\n", attr_name));
            out.push_str("    {\n");
            out.push_str(&format!(
                "        let name = v8::String::new(scope, \"{}\").unwrap();\n", attr_name));
            out.push_str(&format!(
                "        let getter = v8::FunctionTemplate::builder_raw({}_get_{}).build(scope);\n", fn_name, idx));
            if m.readonly {
                out.push_str("        proto.set_accessor_property(name.into(), Some(getter), None, v8::PropertyAttribute::NONE);\n");
            } else {
                out.push_str(&format!(
                    "        let setter = v8::FunctionTemplate::builder_raw({}_set_{}).build(scope);\n", fn_name, idx));
                out.push_str("        proto.set_accessor_property(name.into(), Some(getter), Some(setter), v8::PropertyAttribute::NONE);\n");
            }
            out.push_str("    }\n");
        }

        if m.kind == "operation" {
            let op_name = m.name.as_deref().unwrap_or("unknown");
            out.push_str(&format!(
                "    // method: {}()\n", op_name));
            out.push_str("    {\n");
            out.push_str(&format!(
                "        let name = v8::String::new(scope, \"{}\").unwrap();\n", op_name));
            out.push_str(&format!(
                "        let func_tmpl = v8::FunctionTemplate::builder_raw({}_op_{}).build(scope);\n", fn_name, idx));
            out.push_str("        func_tmpl.set_class_name(name);\n");
            out.push_str("        proto.set(name.into(), func_tmpl.into());\n");
            out.push_str("    }\n");
        }
    }

    out.push_str("\n    tmpl\n");
    out.push_str("}\n");
    out
}

/// Generate the install_all function for generated/mod.rs.
/// Creates templates in topological order, handles parent wiring,
/// registers constructors on global with DONT_ENUM.
pub fn generate_install_all(definitions: &[Definition], sorted: &[String], domain_of: &BTreeMap<String, String>) -> String {
    let mut by_name: BTreeMap<String, &Definition> = BTreeMap::new();
    for def in definitions {
        if let Some(name) = &def.name {
            if def.kind == "interface" { by_name.insert(name.clone(), def); }
        }
    }

    let mut out = String::new();
    out.push_str("//! Generated install_all — creates all templates in topological order.\n\n");
    out.push_str("use v8::Local;\nuse v8::Object;\nuse v8::FunctionTemplate;\n\n");

    out.push_str("/// Empty constructor (cannot be inlined — referenced by each template).\n");
    out.push_str("unsafe extern \"C\" fn empty_constructor(_info: *const v8::FunctionCallbackInfo) {}\n\n");

    out.push_str("pub fn install_all(scope: &v8::PinScope<'_, '_>, global: Local<Object>) {\n");
    out.push_str("    let mut templates: std::collections::HashMap<&str, v8::Local<FunctionTemplate>> = std::collections::HashMap::new();\n\n");

    for name in sorted {
        let def = match by_name.get(name) { Some(d) => d, None => continue };
        let fn_name = type_mapper::idl_name_to_rust(name);
        let domain = domain_of.get(name).map(|d| d.as_str()).unwrap_or("web_apis");
        let domain_mod = domain.replace('-', "_");

        // Parent lookup
        let parent_code = match &def.inheritance {
            Some(p) => format!("templates.get(\"{}\").copied()", p),
            None => "None".to_string(),
        };

        out.push_str(&format!(
            "    let tmpl_{0} = super::{dom}::create_{0}_template(scope, {parent});\n",
            fn_name,
            dom = domain_mod,
            parent = parent_code,
        ));
        out.push_str(&format!(
            "    templates.insert(\"{}\", tmpl_{});\n", name, fn_name));
    }

    out.push_str("\n    // Register constructors on global (non-enumerable)\n");
    for name in sorted {
        let def = match by_name.get(name) { Some(d) => d, None => continue };
        let fn_name = type_mapper::idl_name_to_rust(name);

        // Skip NoInterfaceObject
        let ea = process_interface_ea(def);
        if ea.no_interface_object {
            out.push_str(&format!("    // {}: NoInterfaceObject — skip global registration\n", name));
            continue;
        }

        out.push_str(&format!(
            "    if let Some(ctor_{0}) = tmpl_{0}.get_function(scope) {{\n", fn_name));
        out.push_str(&format!(
            "        let name_{0} = v8::String::new(scope, \"{1}\").unwrap();\n", fn_name, name));
        out.push_str(&format!(
            "        global.define_own_property(scope, name_{0}.into(), ctor_{0}.into(), v8::PropertyAttribute::DONT_ENUM);\n", fn_name));
        out.push_str("    }\n");
    }

    out.push_str("}\n");
    out
}

/// Generate mod.rs that aggregates all domain modules.
pub fn generate_mod_rs(domains: &[String]) -> String {
    let mut out = String::new();
    out.push_str("//! Generated FunctionTemplate stubs.\n\n");
    for domain in domains {
        out.push_str(&format!("pub mod {};\n", domain.replace('-', "_")));
    }
    out.push_str("\npub mod install_all;\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{Definition, MemberData};

    #[test]
    fn test_simple_interface_has_tostringtag() {
        let def = Definition {
            kind: "interface".into(), name: Some("Foo".into()), source: Some("w3c".into()),
            inheritance: None, ext_attrs: vec![], partial: false,
            values: vec![], target: None, includes: None,
            members: vec![MemberData {
                kind: "attribute".into(), name: Some("bar".into()),
                idl_type: Some("DOMString".into()), readonly: false,
                return_type: None, arguments: vec![],
            }],
        };
        let fn_name = type_mapper::idl_name_to_rust("Foo");
        let ea = process_interface_ea(&def);
        let code = generate_template_function(&def, &ea, &fn_name);
        assert!(code.contains("get_to_string_tag"), "toStringTag missing");
        assert!(code.contains("\"Foo\""), "class name missing");
    }

    #[test]
    fn test_operation_generates_callback() {
        let def = Definition {
            kind: "interface".into(), name: Some("Bar".into()), source: Some("w3c".into()),
            inheritance: None, ext_attrs: vec![], partial: false,
            values: vec![], target: None, includes: None,
            members: vec![MemberData {
                kind: "operation".into(), name: Some("doThing".into()),
                idl_type: None, readonly: false,
                return_type: Some("undefined".into()), arguments: vec![],
            }],
        };
        let cb = generate_callbacks(&def, "bar");
        assert!(cb.contains("bar_op_1"), "operation callback missing");
        assert!(cb.contains("doThing") == false, "op name should not be in callback code");
    }
}
